### ISSUE TITLE
scalable variant

### ISSUE THREAD

**Issue by CodeFromAnywhere** [transitive-bullshit/kindle-ai-export#3]
can we do this using browserbase.com + some ffmpeg api? this would make it scale. 

I'd pay for a SaaS API that could it in the background and get text (and maybe audio) for ALL of my books, without having to install anything.

**Comment by transitive-bullshit** [comment]
Thanks for opening the issue, wynand 🙏 

I tried browserbase but the kindle reader doesn't render correctly; the only thing I could think of since it was using proxies and TLS spoofing is that the reader may depend on webgl or something which isn't supported out of the box on browserbase's vm.

Other than that, I'm not really interested in selling any type of service for this. That'd be a very quick way to get into legal trouble; as the readme disclaimer states, this is meant purely for educational & personal purposes only.

Cheers
